//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelDruck.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=IBMDA400.DataSource.1;Data Source=A61GM;Persist Security Info=True;Passw" +
            "ord=pbaspm1;User ID=pbaspm;Initial Catalog=A61GM")]
        public string constrAS400 {
            get {
                return ((string)(this["constrAS400"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SRVSQL;Initial Catalog=_Teilestamm_PMDM;Integrated Security=True")]
        public string constrMSsql {
            get {
                return ((string)(this["constrMSsql"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.176.251.72\\Stockroom-GreenLabel")]
        public string conPrinterGreen {
            get {
                return ((string)(this["conPrinterGreen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SRVSQL;Initial Catalog=_Datenstamm_PMDM;Integrated Security=True")]
        public string constrMssql2 {
            get {
                return ((string)(this["constrMssql2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gv9182@pmdm.de")]
        public string SendEMailTo {
            get {
                return ((string)(this["SendEMailTo"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ntses01.ev.minebea.local")]
        public string EmailHost {
            get {
                return ((string)(this["EmailHost"]));
            }
            set {
                this["EmailHost"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gv9018@pmdm.de, gv9081@pmdm.de, gv9093@pmdm.de, gv9519@pmdm.de, gv9616@pmdm.de")]
        public string EmailGefahr {
            get {
                return ((string)(this["EmailGefahr"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.176.250.108\\Stockroom-NoQC-Label")]
        public string conPrinterWhite {
            get {
                return ((string)(this["conPrinterWhite"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.176.2.5\\EasyCoder")]
        public string conPrinterPDF {
            get {
                return ((string)(this["conPrinterPDF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.176.251.72\\Stockroom-GreenLabel")]
        public string conPrinterIQC {
            get {
                return ((string)(this["conPrinterIQC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.120.30.25\\CAB_EOS")]
        public string conPrinterThai {
            get {
                return ((string)(this["conPrinterThai"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.173.1.36\\Industrial-Label")]
        public string conPrinterSK {
            get {
                return ((string)(this["conPrinterSK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\pkeprintsap\\QA-TOSHIBA")]
        public string conPrinterSK_KE {
            get {
                return ((string)(this["conPrinterSK_KE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\pkeprintsap\\QA-TOSHIBA-PRODUCTION")]
        public string conPrinterSK_KE2 {
            get {
                return ((string)(this["conPrinterSK_KE2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.176.250.108\\IQC-Label-red")]
        public string conPrinterDE_RedLabel {
            get {
                return ((string)(this["conPrinterDE_RedLabel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.176.250.108\\Stockroom-NoQC-Label")]
        public string ConPrinterDE_Zebra {
            get {
                return ((string)(this["ConPrinterDE_Zebra"]));
            }
        }
    }
}
